# Generated by Django 2.2.4 on 2019-09-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joinedDate',
        ),
    ]
