# Generated by Django 2.2.5 on 2019-09-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0006_auto_20190918_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_Name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_Name',
            new_name='lastName',
        ),
    ]
