# Generated by Django 2.2.5 on 2019-09-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0007_auto_20190918_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isSeller',
        ),
        migrations.AddField(
            model_name='customer',
            name='isSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='isSeller',
            field=models.BooleanField(default=True),
        ),
    ]
