# Generated by Django 2.2.5 on 2019-09-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0008_auto_20190920_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='isSeller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='isSeller',
        ),
        migrations.AddField(
            model_name='user',
            name='isSeller',
            field=models.BooleanField(default=False),
        ),
    ]
