# Generated by Django 2.2.5 on 2019-10-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0010_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direct.Seller'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direct.Card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direct.Customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direct.Product'),
        ),
    ]
