# Generated by Django 2.2.5 on 2019-10-11 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0011_auto_20191012_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direct.Seller'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direct.Card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direct.Customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direct.Product'),
        ),
    ]
